### ISSUE TITLE
About the drawing of frequency-amplitude graphs

### ISSUE THREAD

**Issue by QixuanPeng** [liun-online/SpCo#1]
Dear author

I am very interested in some of the experiments in this paper, could you tell me more about the frequency-amplitude graphs (as shown in Figure 6 in the paper)? How did you draw it? In particular, what is the formula for calculating amplitude, expressed in the paper as φ (λ)? We'd really appreciate it if we could get this part of the code. Looking forward to your reply.

Yours, 
Qixuan Peng

**Comment by liun-online** [comment]
Thank you for your attention! This part of the code has not been reserved, but I can tell you the process. Take PPR matrix for example, denoted as P.

We first decompose normalized Laplacian matrix L to get eigenvectors u and eigenvalues λ. Then, we rearrange the eigenvalues in an ascending order, and the eigenvectors are also reordered correspondingly. Next, we utilze eq.(2) to calculate the changed eigenvalues, where ΔA=P-L and ΔD=D_P-D_L (D_P and D_L are diagonal matrix whose diagonal elements are the row sums of PPR and Laplacian), and we will get Δλ. Finally, λ' = Δλ + λ, and λ' are the eigenvalues of PPR matrix.

For each subfigure in fig(6), the x-axis means the λ of Laplacian in ascending order (frequency), and y-axis means the λ' of target augmentation (amplitude).

If you meet any problem in reproducing, please come back to me again.

**Comment by QixuanPeng** [comment]
Thank you for your detailed reply. It helps us a lot.
